import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const fontAOT = localFont({
  src: "./fonts/RockwellCondensed.woff",
  variable: "--font-aot",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontAOT.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
